version: '2'
services:
    backend:
        build: ./backend
        image: realskill/backend:latest
        expose:
            - "3000"
        ports:
             - "3000:3000"
        volumes:
            - $CERTS_DIR/:/certs
        environment:
            NODE_TLS_REJECT_UNAUTHORIZED: 0
            DOCKER_HOST: $DOCKER_MANAGER_HOST
            DOCKER_PORT: $DOCKER_MANAGER_PORT
            CA: /certs/ca.pem
            CERT: /certs/cert.pem
            CERT_KEY: /certs/key.pem
    fake-service:
        build: ./fake-service
        image: realskill/fake-service:latest
        expose:
            - "8080"
    slave:
        build: ./task-executor-nodejs
        image: realskill/task-executor-nodejs:latest

