version: '2'
services:
  backend:
    extends:
      file: docker-compose-base.yml
      service: backend
    volumes:
      - $CERTS_DIR/:/certs
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      DOCKER_HOST: $DOCKER_MANAGER_HOST
      DOCKER_PORT: $DOCKER_MANAGER_PORT
      CA: /certs/ca.pem
      CERT: /certs/cert.pem
      CERT_KEY: /certs/key.pem
  fake-service:
    extends:
      file: docker-compose-base.yml
      service: fake-service
  slave:
    extends:
      file: docker-compose-base.yml
      service: slave

