version: '2'
services:
  consul:
    image: progrium/consul
    ports:
      - "8500:8500"
    command: -server -bootstrap
  manager:
    image: swarm
    ports:
      - "4000:4000"
    command: manage -H :4000  --replication --advertise $DOCKER0_IP:4000 --engine-refresh-min-interval 5s --engine-refresh-max-interval 6s --heartbeat 5s consul://consul:8500
    links:
      - consul
  agent:
    image: swarm
    command: join --advertise $DOCKER0_IP:2376 --delay 5s consul://consul:8500
    links:
      - consul
      - manager
  backend:
    extends:
      file: docker-compose-base.yml
      service: backend
    environment:
      DOCKER_HOST: manager
      DOCKER_PORT: 4000
    links:
      - manager
  fake-service:
    extends:
      file: docker-compose-base.yml
      service: fake-service
  slave:
    extends:
      file: docker-compose-base.yml
      service: slave
